### ISSUE TITLE
 "webpack" executable not found in windows environment.

### ISSUE THREAD

**Issue by Odomontois** [nouhoum/play-react-webpack#2]
I'm getting an error during `run` task abount missing "webpack".
Webpack module is installed both in global and project level node_modules, so I can run `webpack --watch` in project folder, but it can't still be found during hook execution.

Detailed error output:

> java.io.IOException: Cannot run program "webpack" (in directory "C:\prog\projects\SBT\boogle-ms"): CreateProcess error=2, The system cannot find the file specified
>         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1042)
> Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
>         at java.lang.ProcessImpl.create(Native Method)
>         at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
>         at java.lang.ProcessImpl.start(ProcessImpl.java:137)
>         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1023)

I have 

> > npm --version
> 3.9.3

and 

> sbt.version=0.13.11

error output from sbt

> [boogle-ms] $ last compile:run
> java.io.IOException: Cannot run program "webpack" (in directory "C:\prog\projects\SBT\boogle-ms"): CreateProcess error=2, The system cannot find the file specified
>         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1042)
>         at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
>         at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:126)
>         at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:125)
>         at Webpack$WebpackHook$2$.beforeStarted(Webpack.scala:12)
>         at play.runsupport.Reloader$$anonfun$13.apply(Reloader.scala:214)
>         at play.runsupport.Reloader$$anonfun$13.apply(Reloader.scala:214)
>         at play.runsupport.RunHook$RunHooksRunner$$anonfun$run$extension$1.apply(RunHook.scala:60)
>         at play.runsupport.RunHook$RunHooksRunner$$anonfun$run$extension$1.apply(RunHook.scala:58)
>         at scala.collection.immutable.List.foreach(List.scala:318)
>         at play.runsupport.RunHook$RunHooksRunner$.run$extension(RunHook.scala:58)
>         at play.runsupport.Reloader$.startDevMode(Reloader.scala:214)
>         at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:74)
>         at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$sbt$run$PlayRun$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:74)
>         at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:100)
>         at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:53)
>         at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
>         at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
>         at sbt.std.Transform$$anon$4.work(System.scala:63)
>         at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
>         at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
>         at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
>         at sbt.Execute.work(Execute.scala:237)
>         at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
>         at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
>         at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
>         at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
> Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
>         at java.lang.ProcessImpl.create(Native Method)
>         at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
>         at java.lang.ProcessImpl.start(ProcessImpl.java:137)
>         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1023)
>         at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
>         at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:126)
>         at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:125)
>         at Webpack$WebpackHook$2$.beforeStarted(Webpack.scala:12)
>         at play.runsupport.Reloader$$anonfun$13.apply(Reloader.scala:214)
>         at play.runsupport.Reloader$$anonfun$13.apply(Reloader.scala:214)
>         at play.runsupport.RunHook$RunHooksRunner$$anonfun$run$extension$1.apply(RunHook.scala:60)
>         at play.runsupport.RunHook$RunHooksRunner$$anonfun$run$extension$1.apply(RunHook.scala:58)
>         at scala.collection.immutable.List.foreach(List.scala:318)
>         at play.runsupport.RunHook$RunHooksRunner$.run$extension(RunHook.scala:58)
>         at play.runsupport.Reloader$.startDevMode(Reloader.scala:214)
>         at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:74)
>         at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$sbt$run$PlayRun$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:74)
>         at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:100)
>         at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:53)
>         at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
>         at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
>         at sbt.std.Transform$$anon$4.work(System.scala:63)
>         at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
>         at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
>         at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
>         at sbt.Execute.work(Execute.scala:237)
>         at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
>         at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
>         at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
>         at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
> [error](compile:run) java.io.IOException: Cannot run program "webpack" (in directory "C:\prog\projects\SBT\boogle-ms"): CreateProcess error=2, The system cannot find the file spe
> cified

**Comment by gmsa** [comment]
Did you manage to fix this? How?

**Comment by ekastimo** [comment]
Hello, this may Help some one, `sys.process._` doesn't execute a shell commands directly, it executes an executable(.exe file) with arguments. So comands Like `ls` , `dir` which have executables all work fine but webpack won't work directly.
However, we can pass the webpack commad to `cmd`to have it executed, i.e.
`Process("cmd /c \"webpack\"", base).run()`
And everything will work fine. 

Note: Use `sh` in place of `cmd` for Linux
Regards.

**Comment by sakar-sr** [comment]
hello ekastimo

i tried your method, but gives an error saying 

'webpack' is not recognized as an internal or external command,                 operable program or batch file.

please help
good day

**Comment by ekastimo** [comment]
Hello sakar-sr, please make sure you have webpack installed globally using npm
i.e.  `npm install -g webpack`

**Comment by sakar-sr** [comment]
Hello ekastimo,

Thanks it works like a charm. I tried it with scala play and vue.js and works great.

Have a Nice day
