### ISSUE TITLE
Problem in running webpack

### ISSUE THREAD

**Issue by 23suhail88** [nouhoum/play-react-webpack#3]
Hi,

I am trying to use this as a reference for my project. while doint activator run i am getting error of not ruuning webpack. i am attaching the stack trace. please suggest for the same.

![webpack](https://cloud.githubusercontent.com/assets/19284570/16143153/84c8216a-3488-11e6-9214-fdc8b6df0899.png)

**Comment by selfius** [comment]
Hey, look like it can't find webpack executable in you PATH. I guess you should run something like `npm -g install webpack`, that should do the trick

**Comment by 23suhail88** [comment]
While running npm -g install webpack comman d i am getting following error. activator run is still giving the same error.
Any suggestions.

C:\Workspaces\play-react-webpack-master>npm -g install webpack
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
C:\Users\suhail.akhtar\AppData\Roaming\npm\webpack -> C:\Users\suhail.akhtar\App
Data\Roaming\npm\node_modules\webpack\bin\webpack.js
C:\Users\suhail.akhtar\AppData\Roaming\npm
`-- webpack@1.13.1
  +-- acorn@3.2.0
  +-- async@1.5.2
  +-- clone@1.0.2
  +-- enhanced-resolve@0.9.1
  | +-- graceful-fs@4.1.4
  |`-- memory-fs@0.2.0
  +-- interpret@0.6.6
  +-- loader-utils@0.2.15
  | +-- big.js@3.1.3
  | +-- emojis-list@2.0.1
  | +-- json5@0.5.0
  | `-- object-assign@4.1.0
  +-- memory-fs@0.3.0
  | +-- errno@0.1.4
  | |`-- prr@0.0.0
  | `-- readable-stream@2.1.4
  |   +-- buffer-shims@1.0.0
  |   +-- core-util-is@1.0.2
  |   +-- inherits@2.0.1
  |   +-- isarray@1.0.0
  |   +-- process-nextick-args@1.0.7
  |`-- util-deprecate@1.0.2
  +-- mkdirp@0.5.1
  | `-- minimist@0.0.8
  +-- node-libs-browser@0.5.3
  | +-- assert@1.4.1
  | +-- browserify-zlib@0.1.4
  | |`-- pako@0.2.8
  | +-- buffer@3.6.0
  | | +-- base64-js@0.0.8
  | | `-- ieee754@1.1.6
  | +-- console-browserify@1.1.0
  | |`-- date-now@0.1.4
  | +-- constants-browserify@0.0.1
  | +-- crypto-browserify@3.2.8
  | | +-- pbkdf2-compat@2.0.1
  | | +-- ripemd160@0.2.0
  | | `-- sha.js@2.2.6
  | +-- domain-browser@1.1.7
  | +-- events@1.1.0
  | +-- http-browserify@1.7.0
  | |`-- Base64@0.2.1
  | +-- https-browserify@0.0.0
  | +-- os-browserify@0.1.2
  | +-- path-browserify@0.0.0
  | +-- process@0.11.5
  | +-- punycode@1.4.1
  | +-- querystring-es3@0.2.1
  | +-- readable-stream@1.1.14
  | | `-- isarray@0.0.1
  | +-- stream-browserify@1.0.0
  | |`-- readable-stream@1.1.14
  | |   `-- isarray@0.0.1
  | +-- string_decoder@0.10.31
  | +-- timers-browserify@1.4.2
  | +-- tty-browserify@0.0.0
  | +-- url@0.10.3
  | | +-- punycode@1.3.2
  | |`-- querystring@0.2.0
  | +-- util@0.10.3
  | `-- vm-browserify@0.0.4
  |`-- indexof@0.0.1
  +-- optimist@0.6.1
  | `-- wordwrap@0.0.3
  +-- supports-color@3.1.2
  |`-- has-flag@1.0.0
  +-- tapable@0.1.10
  +-- uglify-js@2.6.3
  | +-- async@0.2.10
  | +-- source-map@0.5.6
  | +-- uglify-to-browserify@1.0.2
  | `-- yargs@3.10.0
  |   +-- camelcase@1.2.1
  |   +-- cliui@2.1.0
  |   | +-- center-align@0.1.3
  |   | | +-- align-text@0.1.4
  |   | | | +-- longest@1.0.1
  |   | | |`-- repeat-string@1.5.4
  |   | | `-- lazy-cache@1.0.4
  |   | +-- right-align@0.1.3
  |   |`-- wordwrap@0.0.2
  |   +-- decamelize@1.2.0
  |   `-- window-size@0.1.0
  +-- watchpack@0.2.9
  | +-- async@0.9.2
  |`-- chokidar@1.5.2
  |   +-- anymatch@1.3.0
  |   | +-- arrify@1.0.1
  |   | `-- micromatch@2.3.8
  |   |   +-- arr-diff@2.0.0
  |   |   |`-- arr-flatten@1.0.1
  |   |   +-- array-unique@0.2.1
  |   |   +-- braces@1.8.5
  |   |   | +-- expand-range@1.8.2
  |   |   | | `-- fill-range@2.2.3
  |   |   | |   +-- is-number@2.1.0
  |   |   | |   +-- isobject@2.1.0
  |   |   | |`-- randomatic@1.1.5
  |   |   | +-- preserve@0.2.0
  |   |   | `-- repeat-element@1.1.2
  |   |   +-- expand-brackets@0.1.5
  |   |   |`-- is-posix-bracket@0.1.1
  |   |   +-- extglob@0.3.2
  |   |   +-- filename-regex@2.0.0
  |   |   +-- kind-of@3.0.3
  |   |   | `-- is-buffer@1.1.3
  |   |   +-- normalize-path@2.0.1
  |   |   +-- object.omit@2.0.0
  |   |   | +-- for-own@0.1.4
  |   |   | |`-- for-in@0.1.5
  |   |   | `-- is-extendable@0.1.1
  |   |   +-- parse-glob@3.0.4
  |   |   | +-- glob-base@0.3.0
  |   |   |`-- is-dotfile@1.0.2
  |   |   `-- regex-cache@0.4.3
  |   |     +-- is-equal-shallow@0.1.3
  |   |`-- is-primitive@2.0.0
  |   +-- async-each@1.0.0
  |   +-- glob-parent@2.0.0
  |   +-- is-binary-path@1.0.1
  |   | `-- binary-extensions@1.4.1
  |   +-- is-glob@2.0.1
  |   |`-- is-extglob@1.0.0
  |   +-- path-is-absolute@1.0.0
  |   `-- readdirp@2.0.0
  |`-- minimatch@2.0.10
  |       `-- brace-expansion@1.1.5
  |         +-- balanced-match@0.4.1
  |`-- concat-map@0.0.1
  `-- webpack-core@0.6.8
    +-- source-list-map@0.1.6
`-- source-map@0.4.4
      `-- amdefine@1.0.0

npm WARN optional Skipping failed optional dependency /webpack/chokidar/fsevents
:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.12

C:\Workspaces\play-react-webpack-master>activator run
[info] Loading project definition from C:\Workspaces\play-react-webpack-master\p
roject
[info] Set current project to play-react-webpack (in build file:/C:/Workspaces/p
lay-react-webpack-master/)

java.io.IOException: Cannot run program "webpack" (in directory "C:\Workspaces\p
lay-react-webpack-master"): CreateProcess error=2, The system cannot find the fi
le specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find th
e file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error](compile:run) java.io.IOException: Cannot run program "webpack" (in dire
ctory "C:\Workspaces\play-react-webpack-master"): CreateProcess error=2, The sys
tem cannot find the file specified
[error] Total time: 0 s, completed Jun 21, 2016 12:51:21 PM

**Comment by ekastimo** [comment]
Hello, this may Help some one, `sys.process._` doesn't execute a shell commands directly, it executes an executable(.exe file) with arguments. So comands Like `ls` , `dir` which have executables all work fine but webpack won't work directly.
However, we can pass the webpack commad to `cmd` to have it executed, i.e.
`Process("cmd /c \"webpack\"", base).run(`)
And everything will work fine.

Note: Use `sh` in place of `cmd`for Linux
Regards.

**Comment by source-nerd** [comment]
Hello after adding your Process for windows, I am getting error at base.

**Comment by teimuraz** [comment]
I had this issue too. There are two solutions: either install webpack globally (not recommended), or second: adjust the path to webpack in the source:

1. /webpack.sbt, line 4:
Replace ` Process("webpack", file) !` with ` Process("./node_modules/.bin/webpack", file) !`


2. /project/Webpack.scala
replace all occurences `Process("webpack` with `Process("./node_modules/.bin/webpack`
